### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by zdnahom** [codedit334/Leaderboard#6]
Hi @codedit334 ,
You have built such an amazing website well done 👏 . But I've noticed some issues in your project
<img src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlight
✔️ Linter error-free
✔️ Great commit message
✔️ Great project structure

## Comments

❌ kindly remove the console.log from this line since it's not a good practice to leave the console.log() in your codebase .https://github.com/codedit334/Leaderboard/blob/365c6b21c832f2eb5f7186079d556f83c99171eb/src/modules/get_api_id.js#L15

## Reviewers
@zdnahom 
@Stephen-Adom
@ilyassatlassi

**Comment by codedit334** [comment]
Thank you @zdnahom, I'll make sure it won't stay there!
